// 使い方: node render5.mjs <モジュール...> <出力PNG> [倍率(既定は大きさから自動)] — 大きな絵を1枚のPNGにする（目で確かめる用）。背景は暗い紫。
import fs from "fs"; import path from "path"; import { pathToFileURL } from "url"; import { chromium } from "playwright-core";
const args = process.argv.slice(2); const out = args.find((a) => a.endsWith(".png")); const rest = args.filter((a) => a !== out && !/^\d+$/.test(a)); const Zarg = args.find((a) => /^\d+$/.test(a));
const files = rest.flatMap((a) => (fs.statSync(a).isDirectory() ? fs.readdirSync(a).filter((f) => f.endsWith(".mjs")).sort().map((f) => path.join(a, f)) : [a]));
const items = []; for (const f of files) { try { const m = await import(pathToFileURL(path.resolve(f)).href + "?t=" + Date.now()); items.push({ name: m.name, file: path.basename(f, ".mjs"), rows: m.rows, pal: m.pal, n: m.rows.length }); } catch (e) { console.log("NG", f, String(e).split("\n").slice(0, 2).join(" ")); } }
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" }); const p = await b.newPage();
const d = await p.evaluate(({ items, Zarg }) => { const maxN = Math.max(...items.map((i) => i.n)), Z = Zarg ? +Zarg : Math.max(2, Math.floor(700 / maxN)); const cols = Math.min(items.length, Math.max(1, Math.floor(1800 / (maxN * Z + 12)))); const cw = maxN * Z + 12, ch = maxN * Z + 34, rowsN = Math.ceil(items.length / cols); const c = document.createElement("canvas"); c.width = cols * cw; c.height = rowsN * ch; const x = c.getContext("2d"); x.fillStyle = "#3d3160"; x.fillRect(0, 0, c.width, c.height); x.font = "13px sans-serif";
  items.forEach((it, k) => { const ox = (k % cols) * cw + 6, oy = Math.floor(k / cols) * ch + 4; x.fillStyle = "#4a3d75"; x.fillRect(ox - 3, oy - 2, cw - 6, ch - 4); it.rows.forEach((r, yy) => [...r].forEach((kk, xx) => { if (it.pal[kk]) { x.fillStyle = it.pal[kk]; x.fillRect(ox + xx * Z, oy + yy * Z, Z, Z); } else if (kk !== ".") { x.fillStyle = "#f0f"; x.fillRect(ox + xx * Z, oy + yy * Z, Z, Z); } })); x.fillStyle = "#fff"; x.fillText(it.file + " " + it.n + "×" + it.n + " " + new Set(it.rows.join("").replace(/\./g, "")).size + "色", ox, oy + it.n * Z + 16); });
  return c.toDataURL("image/png"); }, { items, Zarg });
fs.writeFileSync(out, Buffer.from(d.split(",")[1], "base64")); await b.close(); console.log(items.length, "点 →", out);
