import type { JobData, JobId } from "./types";

/** 熟練度の最大（☆）。上級ジョブの解放条件（15☆）と同じ値。 */
export const MAX_STARS = 15;
/** 天神・悪神ジョブの熟練度の最大（☆）。15個の特技を、☆1〜10で覚える（☆によっては2つ）。 */
export const DIVINE_MAX_STARS = 10;

/** そのジョブの熟練度の最大（☆）。 */
export function maxStarsOf(jobId: JobId): number {
  return JOBS_BY_ID[jobId]?.maxStars ?? MAX_STARS;
}

/** 初期ジョブ8種（`docs/design/jobs.md` 2章）。数値は仮で、今後シミュレーションで調整する。 */
export const INITIAL_JOBS: JobData[] = [
  {
    id: "sword-guard",
    name: "剣衛士",
    reading: "けんえいし",
    role: "攻防のバランスが良い近接アタッカー兼盾役",
    statBonus: { attack: 3, defense: 3 },
    bonusPerStar: { attack: 1, defense: 1 },
    skills: [
      { name: "試し斬り", requiredStars: 1, description: "軽く踏みこみ、敵1体を斬る", battle: { mpCost: 1, powerMultiplier: 1.3 } },
      { name: "踏み込み斬り", requiredStars: 2, description: "一歩踏み込んで敵1体を強く斬る", battle: { mpCost: 2, powerMultiplier: 1.5 } },
      { name: "構え直し", requiredStars: 3, description: "味方1人の守りを上げる", battle: { mpCost: 2, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.3, turns: 3 } },
      { name: "峰打ちの型", requiredStars: 4, description: "峰で打ち、敵1体のこうげきを下げる", battle: { mpCost: 2, powerMultiplier: 0, effect: "debuff", stat: "attack", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "受け流し", requiredStars: 5, description: "3ターンのあいだ味方1人の守りを上げる", battle: { mpCost: 2, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.4, turns: 3 } },
      { name: "双つ斬り", requiredStars: 6, description: "敵1体に2回続けて斬りつける", battle: { mpCost: 4, powerMultiplier: 0.9, effect: "multi", hits: 2 } },
      { name: "鎧砕き", requiredStars: 7, description: "敵1体の守りを下げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "剣気の一閃", requiredStars: 8, description: "剣気をこめた一閃で、敵1体を斬る", battle: { mpCost: 5, powerMultiplier: 1.9 } },
      { name: "守りの構え斬り", requiredStars: 9, description: "守りを固めたまま、敵1体を斬る", battle: { mpCost: 4, powerMultiplier: 2.0 } },
      { name: "薙ぎ払い", requiredStars: 10, description: "剣を大きく振り、敵全体を斬る", battle: { mpCost: 7, powerMultiplier: 1.0, effect: "damageAll" } },
      { name: "鼓舞の剣", requiredStars: 11, description: "剣をかかげ、味方全体のこうげきを上げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.2, turns: 3 } },
      { name: "三段斬り", requiredStars: 12, description: "敵1体に3回続けて斬りつける", battle: { mpCost: 9, powerMultiplier: 0.9, effect: "multi", hits: 3 } },
      { name: "剣衛の誓い", requiredStars: 13, description: "息を整え、自分の減ったHPの半分を回復する", battle: { mpCost: 10, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "断ち割り", requiredStars: 14, description: "渾身の力で、敵1体を断ち割る", battle: { mpCost: 10, powerMultiplier: 2.6 } },
      { name: "剣衛奥義・千重ね", requiredStars: 15, description: "重ねた剣筋で、敵1体を4回斬る", battle: { mpCost: 16, powerMultiplier: 1.0, effect: "multi", hits: 4 } },
    ],
  },
  {
    id: "fist-fighter",
    name: "拳闘士",
    reading: "けんとうし",
    role: "連続攻撃が得意な高速アタッカー",
    statBonus: { attack: 2, speed: 4 },
    bonusPerStar: { attack: 1, speed: 1 },
    skills: [
      { name: "軽打", requiredStars: 1, description: "すばやい拳で敵1体を打つ", battle: { mpCost: 1, powerMultiplier: 1.2 } },
      { name: "二連打", requiredStars: 2, description: "敵1体に2回続けて殴る", battle: { mpCost: 3, powerMultiplier: 1.0, effect: "multi", hits: 2 } },
      { name: "気息の型", requiredStars: 3, description: "息を整え、味方1人のこうげきを上げる", battle: { mpCost: 2, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "足払い", requiredStars: 4, description: "足をはらい、敵1体のすばやさを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "足さばき", requiredStars: 5, description: "味方1人のすばやさを少し上げる", battle: { mpCost: 2, powerMultiplier: 0, effect: "buff", stat: "speed", mult: 1.3, turns: 3 } },
      { name: "肘落とし", requiredStars: 6, description: "ひじを落とし、敵1体を強く打つ", battle: { mpCost: 4, powerMultiplier: 1.8 } },
      { name: "当て身", requiredStars: 7, description: "急所を打ち、敵1体の動きを止めることがある", battle: { mpCost: 4, powerMultiplier: 0, effect: "sleep", chance: 0.5, turns: 1 } },
      { name: "連ね打ち", requiredStars: 8, description: "重い拳を2回続けて打ちこむ", battle: { mpCost: 5, powerMultiplier: 1.2, effect: "multi", hits: 2 } },
      { name: "乱れ打ち", requiredStars: 9, description: "敵1体に3回続けて殴る", battle: { mpCost: 7, powerMultiplier: 1.1, effect: "multi", hits: 3 } },
      { name: "輪転脚", requiredStars: 10, description: "回りながらの蹴りで、敵全体を打つ", battle: { mpCost: 7, powerMultiplier: 1.0, effect: "damageAll" } },
      { name: "闘気解放", requiredStars: 11, description: "闘気を放ち、味方1人のこうげきを大きく上げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.5, turns: 3 } },
      { name: "震脚の打", requiredStars: 12, description: "地をふみしめた一撃で、敵1体を打つ", battle: { mpCost: 8, powerMultiplier: 2.4 } },
      { name: "息吹", requiredStars: 13, description: "深い呼吸で、自分の減ったHPの半分を回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "五連打", requiredStars: 14, description: "敵1体に5回続けて殴る", battle: { mpCost: 12, powerMultiplier: 0.8, effect: "multi", hits: 5 } },
      { name: "拳闘奥義・百花撃", requiredStars: 15, description: "花びらのように舞う拳で、敵1体を6回打つ", battle: { mpCost: 16, powerMultiplier: 0.85, effect: "multi", hits: 6 } },
    ],
  },
  {
    id: "archer",
    name: "弓術士",
    reading: "きゅうじゅつし",
    role: "会心が出やすい遠距離アタッカー",
    statBonus: { attack: 3, speed: 2 },
    bonusPerStar: { attack: 1, speed: 1 },
    skills: [
      { name: "速射", requiredStars: 1, description: "すばやく矢をつがえ、敵1体を射る", battle: { mpCost: 1, powerMultiplier: 1.2 } },
      { name: "狙い撃ち", requiredStars: 2, description: "当たりやすく、会心が出やすい一射", battle: { mpCost: 2, powerMultiplier: 1.4 } },
      { name: "毒矢", requiredStars: 3, description: "毒をぬった矢で、敵1体を毒にすることがある", battle: { mpCost: 3, powerMultiplier: 0, effect: "poison", chance: 0.7, turns: 4 } },
      { name: "二本射ち", requiredStars: 4, description: "2本の矢を続けて放つ", battle: { mpCost: 3, powerMultiplier: 0.9, effect: "multi", hits: 2 } },
      { name: "足止めの矢", requiredStars: 5, description: "敵1体のすばやさを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "鷹の目", requiredStars: 6, description: "狙いをすまし、味方1人のこうげきを上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "散り矢", requiredStars: 7, description: "広く矢をまき、敵全体を射る", battle: { mpCost: 6, powerMultiplier: 0.9, effect: "damageAll" } },
      { name: "貫き通し", requiredStars: 8, description: "鋭い一射で、敵1体を貫く", battle: { mpCost: 5, powerMultiplier: 2.0 } },
      { name: "急所の一矢", requiredStars: 9, description: "急所をねらう強力な一射で、敵1体を撃つ", battle: { mpCost: 6, powerMultiplier: 2.4 } },
      { name: "眠り矢", requiredStars: 10, description: "眠り草の矢で、敵1体を眠らせることがある", battle: { mpCost: 5, powerMultiplier: 0, effect: "sleep", chance: 0.6, turns: 2 } },
      { name: "鎧通しの矢", requiredStars: 11, description: "鎧のすきまを射て、敵1体の守りを下げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "三本射ち", requiredStars: 12, description: "3本の矢を続けて放つ", battle: { mpCost: 9, powerMultiplier: 1.0, effect: "multi", hits: 3 } },
      { name: "流れ星の矢", requiredStars: 13, description: "高く放った矢が流れ星のように降り、敵全体を射る", battle: { mpCost: 10, powerMultiplier: 1.4, effect: "damageAll" } },
      { name: "一点穿ち", requiredStars: 14, description: "ただ一点をねらい、敵1体を射抜く", battle: { mpCost: 11, powerMultiplier: 3.0 } },
      { name: "弓術奥義・天穿つ雨", requiredStars: 15, description: "天から降る矢の雨が、守りを無視して敵全体を射る", battle: { mpCost: 18, powerMultiplier: 1.0, effect: "pierceAll" } },
    ],
  },
  {
    id: "flame-mage",
    name: "火照術士",
    reading: "かしょうじゅつし",
    role: "攻撃呪文に特化した、MP効率の良い術士",
    statBonus: { maxMp: 8, attack: 1 },
    bonusPerStar: { maxMp: 3 },
    skills: [
      { name: "火照の種火", requiredStars: 1, description: "小さな種火で、敵1体を焼く", battle: { mpCost: 1, powerMultiplier: 1.3 } },
      { name: "火照の灯", requiredStars: 2, description: "小さな火で敵1体を焼く", battle: { mpCost: 2, powerMultiplier: 1.5 } },
      { name: "火照の熱気", requiredStars: 3, description: "熱で、敵1体の守りをゆるめる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "火照の連弾", requiredStars: 4, description: "火の玉を2つ続けて放つ", battle: { mpCost: 4, powerMultiplier: 1.0, effect: "multi", hits: 2 } },
      { name: "火照の波", requiredStars: 5, description: "熱の波で敵全体を焼く", battle: { mpCost: 5, powerMultiplier: 1.0, effect: "damageAll" } },
      { name: "火照の焦がし", requiredStars: 6, description: "やけどで、敵1体に毎ターン傷を負わせることがある", battle: { mpCost: 4, powerMultiplier: 0, effect: "poison", chance: 0.7, turns: 3 } },
      { name: "火照の槍", requiredStars: 7, description: "炎の槍で、敵1体を貫く", battle: { mpCost: 6, powerMultiplier: 2.1 } },
      { name: "火照のたき火", requiredStars: 8, description: "あたたかな火で、味方全体のこうげきを上げる", battle: { mpCost: 7, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.15, turns: 3 } },
      { name: "火照の奔流", requiredStars: 9, description: "強い火で敵1体を焼き尽くす", battle: { mpCost: 8, powerMultiplier: 2.6 } },
      { name: "火照の陽炎", requiredStars: 10, description: "ゆらめく陽炎で、敵全体のこうげきを下げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.8, turns: 3, chance: 0.8 } },
      { name: "火照の大波", requiredStars: 11, description: "大きな熱の波で、敵全体を焼く", battle: { mpCost: 10, powerMultiplier: 1.5, effect: "damageAll" } },
      { name: "火照の三連弾", requiredStars: 12, description: "火の玉を3つ続けて放つ", battle: { mpCost: 11, powerMultiplier: 1.2, effect: "multi", hits: 3 } },
      { name: "火照の炎柱", requiredStars: 13, description: "足もとから炎の柱を立て、敵1体を焼く", battle: { mpCost: 12, powerMultiplier: 3.0 } },
      { name: "火照の燎原", requiredStars: 14, description: "野を焼く炎で、敵全体を焼きはらう", battle: { mpCost: 15, powerMultiplier: 1.9, effect: "damageAll" } },
      { name: "火照奥義・日輪", requiredStars: 15, description: "日輪のような炎が、守りを無視して敵全体を焼く", battle: { mpCost: 22, powerMultiplier: 1.3, effect: "pierceAll" } },
    ],
  },
  {
    id: "ripple-mage",
    name: "水紋術士",
    reading: "すいもんじゅつし",
    role: "回復と防御の呪文に特化した術士",
    statBonus: { maxMp: 8, defense: 1 },
    bonusPerStar: { maxMp: 3 },
    skills: [
      { name: "水紋のしずく", requiredStars: 1, description: "ひとしずくで、味方1人のHPを少し回復する", battle: { mpCost: 2, powerMultiplier: 0, effect: "heal", healRatio: 1.0 } },
      { name: "水紋の癒し", requiredStars: 2, description: "味方1人のHPを回復する", battle: { mpCost: 3, powerMultiplier: 0, effect: "heal", healRatio: 1.6 } },
      { name: "水紋の礫", requiredStars: 3, description: "水の礫で、敵1体を打つ", battle: { mpCost: 2, powerMultiplier: 1.3 } },
      { name: "水紋のさざ波", requiredStars: 4, description: "足もとを波だたせ、敵1体のすばやさを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "水紋の膜", requiredStars: 5, description: "味方1人の守りを上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.4, turns: 3 } },
      { name: "水紋の小雨", requiredStars: 6, description: "やさしい雨で、味方全体のHPを少し回復する", battle: { mpCost: 6, powerMultiplier: 0, effect: "healAll", healRatio: 0.7 } },
      { name: "水紋の深癒し", requiredStars: 7, description: "深い水の力で、味方1人のHPを大きく回復する", battle: { mpCost: 6, powerMultiplier: 0, effect: "heal", healRatio: 2.4 } },
      { name: "水紋の渦", requiredStars: 8, description: "水の渦で、敵全体を打つ", battle: { mpCost: 6, powerMultiplier: 1.0, effect: "damageAll" } },
      { name: "水紋の慈雨", requiredStars: 9, description: "味方全体のHPを少し回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "healAll", healRatio: 1.0 } },
      { name: "水紋の守り歌", requiredStars: 10, description: "水音の歌で、味方全体の守りを上げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.3, turns: 3 } },
      { name: "水紋の眠り波", requiredStars: 11, description: "ゆれる波の音で、敵1体を眠らせることがある", battle: { mpCost: 6, powerMultiplier: 0, effect: "sleep", chance: 0.6, turns: 2 } },
      { name: "水紋の大癒し", requiredStars: 12, description: "味方1人のHPを、たっぷり回復する", battle: { mpCost: 10, powerMultiplier: 0, effect: "heal", healRatio: 3.5 } },
      { name: "水紋の潮流", requiredStars: 13, description: "強い潮の流れで、敵全体を打つ", battle: { mpCost: 11, powerMultiplier: 1.5, effect: "damageAll" } },
      { name: "水紋の大慈雨", requiredStars: 14, description: "大きな雨で、味方全体のHPを回復する", battle: { mpCost: 14, powerMultiplier: 0, effect: "healAll", healRatio: 1.8 } },
      { name: "水紋奥義・満ち潮", requiredStars: 15, description: "満ちてくる潮のように、味方全体のHPを大きく回復する", battle: { mpCost: 20, powerMultiplier: 0, effect: "healAll", healRatio: 2.6 } },
    ],
  },
  {
    id: "wind-mage",
    name: "風唱術士",
    reading: "ふうしょうじゅつし",
    role: "すばやさ強化と状態異常が得意な術士",
    statBonus: { maxMp: 6, speed: 3 },
    bonusPerStar: { maxMp: 2, speed: 1 },
    skills: [
      { name: "風唱のそよぎ", requiredStars: 1, description: "そよ風の刃で、敵1体を切る", battle: { mpCost: 1, powerMultiplier: 1.2 } },
      { name: "風唱の追い風", requiredStars: 2, description: "味方1人のすばやさを上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "speed", mult: 1.3, turns: 3 } },
      { name: "風唱のつむじ", requiredStars: 3, description: "つむじ風で、敵1体を切りきざむ", battle: { mpCost: 3, powerMultiplier: 1.6 } },
      { name: "風唱の目つぶし", requiredStars: 4, description: "砂まじりの風で、敵1体のこうげきを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "attack", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "風唱の眠り唄", requiredStars: 5, description: "敵1体を眠らせることがある（体力の大きい敵には効かない）", battle: { mpCost: 5, powerMultiplier: 0, effect: "sleep", chance: 0.6, turns: 2 } },
      { name: "風唱の惑い歌", requiredStars: 6, description: "まどわす歌で、敵1体を混乱させることがある", battle: { mpCost: 5, powerMultiplier: 0, effect: "confuse", chance: 0.55, turns: 2 } },
      { name: "風唱の二重奏", requiredStars: 7, description: "2つの風の刃で、敵1体を2回切る", battle: { mpCost: 5, powerMultiplier: 1.1, effect: "multi", hits: 2 } },
      { name: "風唱の大追い風", requiredStars: 8, description: "大きな追い風で、味方全体のすばやさを上げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.25, turns: 3 } },
      { name: "風唱の刃", requiredStars: 9, description: "風の刃で敵全体を切る", battle: { mpCost: 8, powerMultiplier: 1.2, effect: "damageAll" } },
      { name: "風唱の鈍り歌", requiredStars: 10, description: "重たい歌で、敵全体のすばやさを下げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "debuffAll", stat: "speed", mult: 0.75, turns: 3, chance: 0.8 } },
      { name: "風唱の鋭風", requiredStars: 11, description: "鋭い風で、敵1体を深く切る", battle: { mpCost: 9, powerMultiplier: 2.4 } },
      { name: "風唱の子守歌", requiredStars: 12, description: "やさしい子守歌で、敵1体を長く眠らせることがある", battle: { mpCost: 9, powerMultiplier: 0, effect: "sleep", chance: 0.75, turns: 3 } },
      { name: "風唱の竜巻", requiredStars: 13, description: "竜巻で、敵全体を巻きあげる", battle: { mpCost: 12, powerMultiplier: 1.6, effect: "damageAll" } },
      { name: "風唱の連奏", requiredStars: 14, description: "4つの風の刃で、敵1体を4回切る", battle: { mpCost: 13, powerMultiplier: 0.9, effect: "multi", hits: 4 } },
      { name: "風唱奥義・天つ風", requiredStars: 15, description: "天から吹きおろす風で、敵全体を切りさく", battle: { mpCost: 20, powerMultiplier: 2.2, effect: "damageAll" } },
    ],
  },
  {
    id: "earth-guard",
    name: "地固衛士",
    reading: "ちこえいし",
    role: "防御と拘束に特化した、パーティ最高クラスの耐久",
    statBonus: { maxHp: 10, defense: 3 },
    bonusPerStar: { maxHp: 4, defense: 1 },
    skills: [
      { name: "地固の打ち", requiredStars: 1, description: "かたい拳で、敵1体を打つ", battle: { mpCost: 1, powerMultiplier: 1.3 } },
      { name: "地固の壁", requiredStars: 2, description: "味方1人の守りを大きく上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.6, turns: 3 } },
      { name: "地固の踏みしめ", requiredStars: 3, description: "地をふみ鳴らし、敵1体のすばやさを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "地固の重打", requiredStars: 4, description: "重い一撃で、敵1体を打つ", battle: { mpCost: 3, powerMultiplier: 1.7 } },
      { name: "かばいの構え", requiredStars: 5, description: "1ターンのあいだ、味方1人の守りを大きく固める", battle: { mpCost: 2, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 2.0, turns: 1 } },
      { name: "地固の砂礫", requiredStars: 6, description: "砂と礫を飛ばし、敵全体を打つ", battle: { mpCost: 5, powerMultiplier: 0.9, effect: "damageAll" } },
      { name: "地固の根", requiredStars: 7, description: "大地に根を張り、自分の減ったHPの半分を回復する", battle: { mpCost: 6, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "地固の砦", requiredStars: 8, description: "味方全体の守りを上げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.3, turns: 3 } },
      { name: "地固の縛り", requiredStars: 9, description: "敵1体の動きを止めることがある（体力の大きい敵には効かない）", battle: { mpCost: 6, powerMultiplier: 0, effect: "sleep", chance: 0.5, turns: 2 } },
      { name: "地固の岩落とし", requiredStars: 10, description: "大岩を落とし、敵1体を打つ", battle: { mpCost: 8, powerMultiplier: 2.4 } },
      { name: "地固の地鳴り", requiredStars: 11, description: "地鳴りで、敵全体のすばやさを下げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "debuffAll", stat: "speed", mult: 0.7, turns: 3, chance: 0.8 } },
      { name: "地固の鉄壁", requiredStars: 12, description: "味方1人の守りを、とても大きく上げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 2.2, turns: 3 } },
      { name: "地固の大地割り", requiredStars: 13, description: "大地を割り、敵全体を打つ", battle: { mpCost: 12, powerMultiplier: 1.6, effect: "damageAll" } },
      { name: "地固の大守り", requiredStars: 14, description: "味方全体の守りを大きく上げる", battle: { mpCost: 14, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.5, turns: 3 } },
      { name: "地固奥義・山崩し", requiredStars: 15, description: "山をも崩す力が、守りを無視して敵全体を打つ", battle: { mpCost: 20, powerMultiplier: 1.1, effect: "pierceAll" } },
    ],
  },
  {
    id: "wanderer",
    name: "旅芸人",
    reading: "たびげいにん",
    role: "支援と変則の効果を扱う、器用貧乏だが腐らない芸人",
    statBonus: { maxHp: 6, maxMp: 4, speed: 1 },
    bonusPerStar: { maxHp: 2, maxMp: 1 },
    skills: [
      { name: "曲投げ", requiredStars: 1, description: "くるりと投げた小道具で、敵1体を打つ", battle: { mpCost: 1, powerMultiplier: 1.2 } },
      { name: "はやし立て", requiredStars: 2, description: "味方全体の攻撃を少し上げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.25, turns: 3 } },
      { name: "おどけ踊り", requiredStars: 3, description: "おどけた踊りで、敵1体のこうげきを下げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "debuff", stat: "attack", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "お手玉打ち", requiredStars: 4, description: "お手玉を2つ続けてぶつける", battle: { mpCost: 3, powerMultiplier: 0.9, effect: "multi", hits: 2 } },
      { name: "びっくり箱", requiredStars: 5, description: "とび出す仕かけで、敵1体を混乱させることがある", battle: { mpCost: 4, powerMultiplier: 0, effect: "confuse", chance: 0.5, turns: 2 } },
      { name: "まくしたて", requiredStars: 6, description: "早口でまくしたて、敵1体のすばやさを下げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "綱渡り", requiredStars: 7, description: "身軽になり、味方1人のすばやさを上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "speed", mult: 1.4, turns: 3 } },
      { name: "子守り歌芸", requiredStars: 8, description: "ゆったりした歌芸で、敵1体を眠らせることがある", battle: { mpCost: 5, powerMultiplier: 0, effect: "sleep", chance: 0.55, turns: 2 } },
      { name: "目くらまし", requiredStars: 9, description: "敵全体の攻撃を下げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.75, turns: 3, chance: 0.8 } },
      { name: "拍手喝采", requiredStars: 10, description: "拍手で場をわかせ、味方全体のすばやさを上げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.2, turns: 3 } },
      { name: "大玉ころがし", requiredStars: 11, description: "大きな玉をころがし、敵全体を打つ", battle: { mpCost: 9, powerMultiplier: 1.2, effect: "damageAll" } },
      { name: "手品の癒し", requiredStars: 12, description: "ふしぎな手品で、味方全体のHPを回復する", battle: { mpCost: 10, powerMultiplier: 0, effect: "healAll", healRatio: 0.9 } },
      { name: "花吹雪", requiredStars: 13, description: "花吹雪で目をうばい、敵全体の守りを下げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "debuffAll", stat: "defense", mult: 0.8, turns: 3, chance: 0.8 } },
      { name: "曲芸三連", requiredStars: 14, description: "曲芸の早わざで、敵1体を3回打つ", battle: { mpCost: 11, powerMultiplier: 1.2, effect: "multi", hits: 3 } },
      { name: "旅芸奥義・大団円", requiredStars: 15, description: "大団円の舞台で、味方全体のこうげきを大きく上げる", battle: { mpCost: 18, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.4, turns: 3 } },
    ],
  },
];

/**
 * 上級ジョブ8種（`docs/design/jobs.md` 3章）。初期ジョブを最大の☆まで育てると解放され、以後は切り替えて使える。
 * 「初期ジョブの、同じ方向性のままの底上げ」（同6章）。特技は、効果つきの特技（複数回・全体・回復）で、すべて戦闘で使える。数値は仮。
 */
export const ADVANCED_JOBS: JobData[] = [
  {
    id: "sword-saint", baseJob: "sword-guard", name: "剛剣聖", reading: "ごうけんせい", role: "攻防とも一段強い、パーティの主力アタッカー兼壁",
    statBonus: { attack: 7, defense: 6 }, bonusPerStar: { attack: 2, defense: 1 },
    skills: [
      { name: "剛の一太刀", requiredStars: 1, description: "重い一太刀で、敵1体を斬る", battle: { mpCost: 3, powerMultiplier: 1.8 } },
      { name: "断空斬", requiredStars: 2, description: "空ごと断つ一太刀で敵1体を斬る", battle: { mpCost: 4, powerMultiplier: 2.0 } },
      { name: "剛剣の構え", requiredStars: 3, description: "味方1人のこうげきを大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.5, turns: 3 } },
      { name: "剣圧", requiredStars: 4, description: "剣の気迫で、敵全体のこうげきを下げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "烈風の連撃", requiredStars: 5, description: "敵1体に2回続けて斬りつける", battle: { mpCost: 6, powerMultiplier: 1.3, effect: "multi", hits: 2 } },
      { name: "鎧断ち", requiredStars: 6, description: "鎧ごと断ち、敵1体の守りを大きく下げる", battle: { mpCost: 5, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.6, turns: 3, chance: 0.85 } },
      { name: "大薙ぎ", requiredStars: 7, description: "大きな薙ぎで、敵全体を斬る", battle: { mpCost: 8, powerMultiplier: 1.4, effect: "damageAll" } },
      { name: "剛剣の守り", requiredStars: 8, description: "味方1人の守りを大きく上げる", battle: { mpCost: 5, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.8, turns: 3 } },
      { name: "不動の一刀", requiredStars: 9, description: "渾身の一刀で敵1体を斬り伏せる", battle: { mpCost: 9, powerMultiplier: 3.0 } },
      { name: "剣聖の号令", requiredStars: 10, description: "号令で、味方全体のこうげきを上げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "三重の太刀", requiredStars: 11, description: "敵1体に3回続けて斬りつける", battle: { mpCost: 12, powerMultiplier: 1.3, effect: "multi", hits: 3 } },
      { name: "闘志の息吹", requiredStars: 12, description: "闘志で、自分の減ったHPの半分を回復する", battle: { mpCost: 10, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "天地両断", requiredStars: 13, description: "天と地を分かつ一刀で、敵1体を斬る", battle: { mpCost: 14, powerMultiplier: 3.6 } },
      { name: "剛剣・大旋", requiredStars: 14, description: "嵐のような剣で、敵全体を斬る", battle: { mpCost: 15, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "剣聖奥義・無双千刃", requiredStars: 15, description: "千の刃のような剣筋で、敵1体を6回斬る", battle: { mpCost: 22, powerMultiplier: 1.0, effect: "multi", hits: 6 } },
    ],
  },
  {
    id: "sky-fist", baseJob: "fist-fighter", name: "天翔拳士", reading: "てんしょうけんし", role: "最速クラスの行動回数を稼ぐ、乱れ撃ちの拳士",
    statBonus: { attack: 4, speed: 8 }, bonusPerStar: { attack: 1, speed: 2 },
    skills: [
      { name: "天翔の打", requiredStars: 1, description: "空をかける一撃で、敵1体を打つ", battle: { mpCost: 2, powerMultiplier: 1.6 } },
      { name: "疾風三連", requiredStars: 2, description: "敵1体に3回続けて殴る", battle: { mpCost: 5, powerMultiplier: 0.9, effect: "multi", hits: 3 } },
      { name: "天翔の構え", requiredStars: 3, description: "味方1人のすばやさを大きく上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "speed", mult: 1.5, turns: 3 } },
      { name: "天翔の崩し", requiredStars: 4, description: "構えを崩し、敵1体の守りを下げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "天翔ノ舞", requiredStars: 5, description: "敵1体に4回続けて殴る", battle: { mpCost: 8, powerMultiplier: 0.85, effect: "multi", hits: 4 } },
      { name: "天翔の昇打", requiredStars: 6, description: "かけ上がる一撃で、敵1体を打つ", battle: { mpCost: 6, powerMultiplier: 2.4 } },
      { name: "天翔の闘気", requiredStars: 7, description: "味方1人のこうげきを大きく上げる", battle: { mpCost: 5, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.5, turns: 3 } },
      { name: "天翔の回し打ち", requiredStars: 8, description: "回りながら、敵全体を打つ", battle: { mpCost: 8, powerMultiplier: 1.3, effect: "damageAll" } },
      { name: "千手乱舞", requiredStars: 9, description: "敵1体に5回続けて殴る", battle: { mpCost: 12, powerMultiplier: 0.8, effect: "multi", hits: 5 } },
      { name: "天翔の気脈", requiredStars: 10, description: "気脈を整え、自分の減ったHPの半分を回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "天翔の当て", requiredStars: 11, description: "気脈を打ち、敵1体の動きを止めることがある", battle: { mpCost: 6, powerMultiplier: 0, effect: "sleep", chance: 0.55, turns: 1 } },
      { name: "天翔の六連", requiredStars: 12, description: "敵1体に6回続けて殴る", battle: { mpCost: 14, powerMultiplier: 0.75, effect: "multi", hits: 6 } },
      { name: "天翔の鉄拳", requiredStars: 13, description: "鉄のような拳で、敵1体を打つ", battle: { mpCost: 13, powerMultiplier: 3.4 } },
      { name: "天翔の嵐拳", requiredStars: 14, description: "嵐のような拳で、敵全体を打つ", battle: { mpCost: 15, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "天翔奥義・流星群拳", requiredStars: 15, description: "流星群のような拳で、敵1体を8回打つ", battle: { mpCost: 22, powerMultiplier: 0.75, effect: "multi", hits: 8 } },
    ],
  },
  {
    id: "hundred-archer", baseJob: "archer", name: "百矢の射手", reading: "ひゃくしのいて", role: "敵全体をまとめて狙える弓の名手",
    statBonus: { attack: 6, speed: 4 }, bonusPerStar: { attack: 2, speed: 1 },
    skills: [
      { name: "剛弓", requiredStars: 1, description: "強い弓で、敵1体を射る", battle: { mpCost: 2, powerMultiplier: 1.7 } },
      { name: "貫きの矢", requiredStars: 2, description: "鋭い一射で敵1体を貫く", battle: { mpCost: 3, powerMultiplier: 1.8 } },
      { name: "毒霧の矢", requiredStars: 3, description: "毒の霧をまとう矢で、敵1体を毒にすることがある", battle: { mpCost: 4, powerMultiplier: 0, effect: "poison", chance: 0.8, turns: 4 } },
      { name: "鷹の眼差し", requiredStars: 4, description: "味方1人のこうげきを大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.5, turns: 3 } },
      { name: "雨矢", requiredStars: 5, description: "矢の雨で敵全体を射る", battle: { mpCost: 7, powerMultiplier: 1.0, effect: "damageAll" } },
      { name: "影縫い", requiredStars: 6, description: "影を射ぬき、敵1体のすばやさを大きく下げる", battle: { mpCost: 5, powerMultiplier: 0, effect: "debuff", stat: "speed", mult: 0.6, turns: 3, chance: 0.85 } },
      { name: "四本射ち", requiredStars: 7, description: "4本の矢を続けて放つ", battle: { mpCost: 9, powerMultiplier: 1.0, effect: "multi", hits: 4 } },
      { name: "眠りの雨矢", requiredStars: 8, description: "眠り草の矢を降らせ、敵1体を眠らせることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "百矢", requiredStars: 9, description: "百の矢で敵全体を射抜く", battle: { mpCost: 12, powerMultiplier: 1.6, effect: "damageAll" } },
      { name: "破魔の矢", requiredStars: 10, description: "清めの矢で、敵1体を射抜く", battle: { mpCost: 10, powerMultiplier: 3.0 } },
      { name: "鎧穿ちの雨", requiredStars: 11, description: "矢の雨で、敵全体の守りを下げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "debuffAll", stat: "defense", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "千里の一矢", requiredStars: 12, description: "遠くからの一矢で、敵1体を射抜く", battle: { mpCost: 13, powerMultiplier: 3.6 } },
      { name: "矢嵐", requiredStars: 13, description: "嵐のような矢で、敵全体を射る", battle: { mpCost: 15, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "連星の矢", requiredStars: 14, description: "星のように連なる矢で、敵1体を6回射る", battle: { mpCost: 16, powerMultiplier: 0.9, effect: "multi", hits: 6 } },
      { name: "射手奥義・天穿ち", requiredStars: 15, description: "天を穿つ矢が、守りを無視して敵全体を射る", battle: { mpCost: 24, powerMultiplier: 1.4, effect: "pierceAll" } },
    ],
  },
  {
    id: "inferno-guide", baseJob: "flame-mage", name: "業火導師", reading: "ごうかどうし", role: "範囲攻撃呪文を極めた炎の導き手",
    statBonus: { maxMp: 16, attack: 2 }, bonusPerStar: { maxMp: 4 },
    skills: [
      { name: "業火の種", requiredStars: 1, description: "激しい火種で、敵1体を焼く", battle: { mpCost: 3, powerMultiplier: 1.8 } },
      { name: "業火", requiredStars: 2, description: "激しい炎で敵1体を焼く", battle: { mpCost: 5, powerMultiplier: 2.2 } },
      { name: "業火の熱波", requiredStars: 3, description: "熱波で、敵全体の守りを下げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "debuffAll", stat: "defense", mult: 0.85, turns: 3, chance: 0.85 } },
      { name: "業火の連弾", requiredStars: 4, description: "炎の玉を3つ続けて放つ", battle: { mpCost: 7, powerMultiplier: 1.0, effect: "multi", hits: 3 } },
      { name: "炎の渦", requiredStars: 5, description: "炎の渦で敵全体を焼く", battle: { mpCost: 9, powerMultiplier: 1.5, effect: "damageAll" } },
      { name: "業火の焦熱", requiredStars: 6, description: "焦がす熱で、敵1体に毎ターン傷を負わせることがある", battle: { mpCost: 5, powerMultiplier: 0, effect: "poison", chance: 0.8, turns: 4 } },
      { name: "業火の柱", requiredStars: 7, description: "炎の柱で、敵1体を焼く", battle: { mpCost: 9, powerMultiplier: 2.8 } },
      { name: "業火の加護", requiredStars: 8, description: "炎の加護で、味方全体のこうげきを上げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.25, turns: 3 } },
      { name: "灼熱の滅", requiredStars: 9, description: "すべてを灼く炎で敵1体を焼き尽くす", battle: { mpCost: 14, powerMultiplier: 3.4 } },
      { name: "業火の大渦", requiredStars: 10, description: "大きな炎の渦で、敵全体を焼く", battle: { mpCost: 14, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "業火の陽炎", requiredStars: 11, description: "陽炎で、敵全体のこうげきを下げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "業火の雨", requiredStars: 12, description: "炎の雨を4つ降らせ、敵1体を焼く", battle: { mpCost: 16, powerMultiplier: 1.3, effect: "multi", hits: 4 } },
      { name: "業火の光断", requiredStars: 13, description: "光断の力をまぜた炎で、敵1体を焼く", battle: { mpCost: 16, powerMultiplier: 3.8 } },
      { name: "業火の終焉", requiredStars: 14, description: "終わりを告げる炎で、敵全体を焼く", battle: { mpCost: 20, powerMultiplier: 2.6, effect: "damageAll" } },
      { name: "業火奥義・天焦がし", requiredStars: 15, description: "天を焦がす炎が、守りを無視して敵全体を焼く", battle: { mpCost: 28, powerMultiplier: 1.7, effect: "pierceAll" } },
    ],
  },
  {
    id: "stream-sage", baseJob: "ripple-mage", name: "清流賢者", reading: "せいりゅうけんじゃ", role: "全体回復を極めた、水の賢者",
    statBonus: { maxMp: 16, defense: 2 }, bonusPerStar: { maxMp: 4 },
    skills: [
      { name: "清流のしずく", requiredStars: 1, description: "澄んだ水で、味方1人のHPを回復する", battle: { mpCost: 3, powerMultiplier: 0, effect: "heal", healRatio: 1.8 } },
      { name: "清流の癒し", requiredStars: 2, description: "味方1人のHPを大きく回復する", battle: { mpCost: 5, powerMultiplier: 0, effect: "heal", healRatio: 2.4 } },
      { name: "清流の盾", requiredStars: 3, description: "味方1人の守りを大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.5, turns: 3 } },
      { name: "清流の礫", requiredStars: 4, description: "水の礫で、敵1体を打つ", battle: { mpCost: 3, powerMultiplier: 1.8 } },
      { name: "清流の慈雨", requiredStars: 5, description: "味方全体のHPを回復する", battle: { mpCost: 10, powerMultiplier: 0, effect: "healAll", healRatio: 1.6 } },
      { name: "清流の守り歌", requiredStars: 6, description: "味方全体の守りを上げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.35, turns: 3 } },
      { name: "清流の渦", requiredStars: 7, description: "水の渦で、敵全体を打つ", battle: { mpCost: 9, powerMultiplier: 1.4, effect: "damageAll" } },
      { name: "清流の深癒し", requiredStars: 8, description: "味方1人のHPを、たっぷり回復する", battle: { mpCost: 9, powerMultiplier: 0, effect: "heal", healRatio: 3.2 } },
      { name: "甦りの雫", requiredStars: 9, description: "味方1人のHPを、ほとんど全快させる", battle: { mpCost: 14, powerMultiplier: 0, effect: "heal", healRatio: 4.0 } },
      { name: "清流の眠り霧", requiredStars: 10, description: "眠りの霧で、敵1体を眠らせることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "清流の大慈雨", requiredStars: 11, description: "大きな雨で、味方全体のHPを大きく回復する", battle: { mpCost: 15, powerMultiplier: 0, effect: "healAll", healRatio: 2.3 } },
      { name: "清流の大波", requiredStars: 12, description: "大波で、敵全体を打つ", battle: { mpCost: 14, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "清流の加護", requiredStars: 13, description: "流れの加護で、味方全体のすばやさを上げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.3, turns: 3 } },
      { name: "清流の命水", requiredStars: 14, description: "命の水で、味方全体のHPを、たっぷり回復する", battle: { mpCost: 20, powerMultiplier: 0, effect: "healAll", healRatio: 3.0 } },
      { name: "賢者奥義・源流", requiredStars: 15, description: "すべての水の源の力で、味方全体のHPを大きく回復する", battle: { mpCost: 26, powerMultiplier: 0, effect: "healAll", healRatio: 4.0 } },
    ],
  },
  {
    id: "gale-dancer", baseJob: "wind-mage", name: "疾風の舞手", reading: "しっぷうのまいて", role: "風の刃で敵全体を切る、すばやい舞い手",
    statBonus: { maxMp: 12, speed: 6 }, bonusPerStar: { maxMp: 3, speed: 2 },
    skills: [
      { name: "舞の一閃", requiredStars: 1, description: "舞うような一閃で、敵1体を切る", battle: { mpCost: 2, powerMultiplier: 1.7 } },
      { name: "疾風の刃", requiredStars: 2, description: "風の刃で敵全体を切る", battle: { mpCost: 7, powerMultiplier: 1.4, effect: "damageAll" } },
      { name: "舞手の足取り", requiredStars: 3, description: "味方1人のすばやさを大きく上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "speed", mult: 1.5, turns: 3 } },
      { name: "惑わしの舞", requiredStars: 4, description: "まどわす舞で、敵1体を混乱させることがある", battle: { mpCost: 6, powerMultiplier: 0, effect: "confuse", chance: 0.65, turns: 2 } },
      { name: "風の舞", requiredStars: 5, description: "舞うように敵1体を3回切る", battle: { mpCost: 8, powerMultiplier: 1.1, effect: "multi", hits: 3 } },
      { name: "鈍りの舞", requiredStars: 6, description: "重たい舞で、敵全体のすばやさを下げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "debuffAll", stat: "speed", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "舞手の旋風", requiredStars: 7, description: "旋風で、敵1体を深く切る", battle: { mpCost: 8, powerMultiplier: 2.6 } },
      { name: "眠りの舞", requiredStars: 8, description: "ゆるやかな舞で、敵1体を眠らせることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "颶風", requiredStars: 9, description: "大きな風で敵全体を吹き飛ばす", battle: { mpCost: 13, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "追い風の舞", requiredStars: 10, description: "味方全体のすばやさを大きく上げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.4, turns: 3 } },
      { name: "乱舞", requiredStars: 11, description: "みだれ舞いで、敵1体を5回切る", battle: { mpCost: 13, powerMultiplier: 0.9, effect: "multi", hits: 5 } },
      { name: "疾風の目つぶし", requiredStars: 12, description: "砂をまく風で、敵全体のこうげきを下げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "天翔ける風", requiredStars: 13, description: "天をかける風で、敵1体を切る", battle: { mpCost: 14, powerMultiplier: 3.6 } },
      { name: "大颶風", requiredStars: 14, description: "大きな颶風で、敵全体を吹き飛ばす", battle: { mpCost: 18, powerMultiplier: 2.5, effect: "damageAll" } },
      { name: "舞手奥義・風神楽", requiredStars: 15, description: "風の神楽が、守りを無視して敵全体を切る", battle: { mpCost: 24, powerMultiplier: 1.3, effect: "pierceAll" } },
    ],
  },
  {
    id: "immovable-guardian", baseJob: "earth-guard", name: "不動の守人", reading: "ふどうのもりびと", role: "だれよりも硬い、大地の守り手",
    statBonus: { maxHp: 20, defense: 6 }, bonusPerStar: { maxHp: 6, defense: 2 },
    skills: [
      { name: "守人の打", requiredStars: 1, description: "重い拳で、敵1体を打つ", battle: { mpCost: 2, powerMultiplier: 1.6 } },
      { name: "不動の一撃", requiredStars: 2, description: "重い拳で敵1体を打つ", battle: { mpCost: 3, powerMultiplier: 1.8 } },
      { name: "不動の構え", requiredStars: 3, description: "味方1人の守りを、とても大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 2.0, turns: 3 } },
      { name: "地鳴らし", requiredStars: 4, description: "地を鳴らし、敵全体のすばやさを下げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "debuffAll", stat: "speed", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "岩砕き", requiredStars: 5, description: "岩をも砕く一撃で敵1体を打つ", battle: { mpCost: 6, powerMultiplier: 2.4 } },
      { name: "守人の砦", requiredStars: 6, description: "味方全体の守りを上げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.4, turns: 3 } },
      { name: "不動の根", requiredStars: 7, description: "大地に根を張り、自分の減ったHPの半分を回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "石化の打", requiredStars: 8, description: "重い一撃で、敵1体をしばらく動けなくすることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.6, turns: 2 } },
      { name: "大地の怒り", requiredStars: 9, description: "大地を揺らして敵全体を打つ", battle: { mpCost: 10, powerMultiplier: 1.6, effect: "damageAll" } },
      { name: "守人の盾陣", requiredStars: 10, description: "盾の陣で、味方全体の守りを大きく上げる", battle: { mpCost: 13, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.6, turns: 3 } },
      { name: "崩しの一撃", requiredStars: 11, description: "敵1体の守りを大きく下げる", battle: { mpCost: 7, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.6, turns: 3, chance: 0.85 } },
      { name: "不動の鉄槌", requiredStars: 12, description: "鉄槌のような一撃で、敵1体を打つ", battle: { mpCost: 13, powerMultiplier: 3.4 } },
      { name: "大地の咆哮", requiredStars: 13, description: "大地の咆哮で、敵全体を打つ", battle: { mpCost: 16, powerMultiplier: 2.2, effect: "damageAll" } },
      { name: "守人の大癒し", requiredStars: 14, description: "大地の力で、味方全体のHPを回復する", battle: { mpCost: 14, powerMultiplier: 0, effect: "healAll", healRatio: 1.5 } },
      { name: "守人奥義・不壊の山", requiredStars: 15, description: "こわれない山のように、味方全体の守りを、とても大きく上げる", battle: { mpCost: 22, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 2.0, turns: 3 } },
    ],
  },
  {
    id: "many-faced-artist", baseJob: "wanderer", name: "千変の遊芸師", reading: "せんぺんのゆうげいし", role: "何が飛び出すか分からない、器用な芸人",
    statBonus: { maxHp: 12, maxMp: 8, speed: 2 }, bonusPerStar: { maxHp: 3, maxMp: 2 },
    skills: [
      { name: "千変の小技", requiredStars: 1, description: "思わぬ小技で、敵1体を打つ", battle: { mpCost: 2, powerMultiplier: 1.7 } },
      { name: "千変の一手", requiredStars: 2, description: "思いがけない一手で敵1体を打つ", battle: { mpCost: 4, powerMultiplier: 2.0 } },
      { name: "からかい芸", requiredStars: 3, description: "からかって、敵1体のこうげきを下げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "debuff", stat: "attack", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "千変の手品", requiredStars: 4, description: "ふしぎな手品で、敵1体を混乱させることがある", battle: { mpCost: 6, powerMultiplier: 0, effect: "confuse", chance: 0.6, turns: 2 } },
      { name: "びっくり乱れ打ち", requiredStars: 5, description: "小道具で敵1体を3回打つ", battle: { mpCost: 7, powerMultiplier: 1.0, effect: "multi", hits: 3 } },
      { name: "喝采の芸", requiredStars: 6, description: "喝采の芸で、味方全体のこうげきを上げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "千変の幻灯", requiredStars: 7, description: "幻灯で、敵全体の守りを下げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "debuffAll", stat: "defense", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "千変の癒し芸", requiredStars: 8, description: "ふしぎな芸で、味方全体のHPを回復する", battle: { mpCost: 11, powerMultiplier: 0, effect: "healAll", healRatio: 1.4 } },
      { name: "大道芸の締め", requiredStars: 9, description: "大がかりな芸で敵全体を打つ", battle: { mpCost: 11, powerMultiplier: 1.8, effect: "damageAll" } },
      { name: "光断の小手品", requiredStars: 10, description: "光断の初級の力を借りた手品で、敵1体を打つ", battle: { mpCost: 11, powerMultiplier: 3.0 } },
      { name: "夢見の芸", requiredStars: 11, description: "夢のような芸で、敵1体を眠らせることがある", battle: { mpCost: 8, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "千変の早業", requiredStars: 12, description: "目にもとまらぬ早業で、敵1体を5回打つ", battle: { mpCost: 14, powerMultiplier: 1.0, effect: "multi", hits: 5 } },
      { name: "千変の大喝采", requiredStars: 13, description: "大喝采で、味方全体のすばやさを上げる", battle: { mpCost: 13, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.35, turns: 3 } },
      { name: "光断の大手品", requiredStars: 14, description: "光断の力を借りた大手品で、敵全体を打つ", battle: { mpCost: 18, powerMultiplier: 2.3, effect: "damageAll" } },
      { name: "遊芸奥義・千変万化", requiredStars: 15, description: "千に変わる芸が、守りを無視して敵全体を打つ", battle: { mpCost: 24, powerMultiplier: 1.4, effect: "pierceAll" } },
    ],
  },
];

/**
 * 天神ジョブ2種・悪神ジョブ2種（`docs/design/jobs.md` 5章）。8神のうち特に対照的な4柱を倒すと、だれでも装備できる。
 * 「上級ジョブより強い」のではなく、「上級ジョブにはない役割と、必ず弱点がある」形（同6章）。数値は仮。
 * - 天神: 女神の巫覡（最高クラスの回復。攻撃は弱い）、純神の聖騎士（最高クラスの守り。攻撃は控えめ）
 * - 悪神: 鬼神の破戒者（最高クラスの攻撃。使うたびにHPを支払う）、蟲神の呪術師（一撃で倒すチャンス。強敵には効かず、確実性がない）
 */
export const DIVINE_JOBS: JobData[] = [
  {
    id: "goddess-shaman", unlockFlag: "god1_defeated", maxStars: DIVINE_MAX_STARS, name: "女神の巫覡", reading: "めがみのふげき", role: "最高クラスの回復。ただし攻撃は弱い",
    statBonus: { maxMp: 20, defense: 2, attack: -4 }, bonusPerStar: { maxMp: 5 },
    skills: [
      { name: "巫覡の祈り", requiredStars: 1, description: "祈りで、味方1人のHPを回復する", battle: { mpCost: 3, powerMultiplier: 0, effect: "heal", healRatio: 2.0 } },
      { name: "恵みの光", requiredStars: 1, description: "味方1人のHPを、たっぷり回復する", battle: { mpCost: 6, powerMultiplier: 0, effect: "heal", healRatio: 3.0 } },
      { name: "巫覡の守り", requiredStars: 2, description: "味方1人の守りを大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.5, turns: 3 } },
      { name: "光の礫", requiredStars: 3, description: "小さな光の礫で、敵1体を打つ（攻撃は弱い）", battle: { mpCost: 2, powerMultiplier: 1.2 } },
      { name: "命の雨", requiredStars: 3, description: "味方全体のHPを回復する", battle: { mpCost: 12, powerMultiplier: 0, effect: "healAll", healRatio: 2.0 } },
      { name: "巫覡の加護", requiredStars: 4, description: "味方全体の守りを上げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.4, turns: 3 } },
      { name: "癒しの舞", requiredStars: 5, description: "癒しの舞で、味方全体のHPを大きく回復する", battle: { mpCost: 14, powerMultiplier: 0, effect: "healAll", healRatio: 2.5 } },
      { name: "巫覡の眠り鈴", requiredStars: 5, description: "鈴の音で、敵1体を眠らせることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "女神の祝福", requiredStars: 6, description: "味方全体のHPを、大きく回復する", battle: { mpCost: 18, powerMultiplier: 0, effect: "healAll", healRatio: 3.5 } },
      { name: "恵みの守り", requiredStars: 7, description: "味方全体のすばやさを上げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.3, turns: 3 } },
      { name: "巫覡の大祈り", requiredStars: 7, description: "大きな祈りで、味方1人のHPを、ほとんど全快させる", battle: { mpCost: 14, powerMultiplier: 0, effect: "heal", healRatio: 5.0 } },
      { name: "慈光", requiredStars: 8, description: "慈しみの光で、味方全体のHPを、たっぷり回復する", battle: { mpCost: 20, powerMultiplier: 0, effect: "healAll", healRatio: 4.0 } },
      { name: "巫覡の清め光", requiredStars: 9, description: "清めの光で、敵全体のこうげきを下げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "女神の涙", requiredStars: 9, description: "女神の涙で、味方全体のHPを、とても大きく回復する", battle: { mpCost: 22, powerMultiplier: 0, effect: "healAll", healRatio: 4.5 } },
      { name: "巫覡奥義・天の恵み", requiredStars: 10, description: "天の恵みで、味方全体のHPを、すべて満たすほど回復する", battle: { mpCost: 30, powerMultiplier: 0, effect: "healAll", healRatio: 6.0 } },
    ],
  },
  {
    id: "pure-paladin", unlockFlag: "god5_defeated", maxStars: DIVINE_MAX_STARS, name: "純神の聖騎士", reading: "じゅんしんのせいきし", role: "最高クラスの守りと反撃。攻撃の伸びは控えめ",
    statBonus: { defense: 10, maxHp: 30, attack: -2 }, bonusPerStar: { defense: 2, maxHp: 6 },
    skills: [
      { name: "聖騎士の構え", requiredStars: 1, description: "味方1人の守りを大きく上げる", battle: { mpCost: 3, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.6, turns: 3 } },
      { name: "聖なる反撃", requiredStars: 1, description: "守りの構えから、敵1体を打つ", battle: { mpCost: 4, powerMultiplier: 2.0 } },
      { name: "白盾", requiredStars: 2, description: "白い盾で、味方全体の守りを上げる", battle: { mpCost: 8, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.3, turns: 3 } },
      { name: "聖騎士の一撃", requiredStars: 3, description: "まっすぐな一撃で、敵1体を打つ", battle: { mpCost: 4, powerMultiplier: 2.0 } },
      { name: "誓いの一閃", requiredStars: 3, description: "誓いをこめた一撃で、敵1体を斬る", battle: { mpCost: 7, powerMultiplier: 2.6 } },
      { name: "聖騎士の祈り", requiredStars: 4, description: "祈りで、味方1人のHPを回復する", battle: { mpCost: 6, powerMultiplier: 0, effect: "heal", healRatio: 2.0 } },
      { name: "清めの光", requiredStars: 5, description: "清めの光で、敵全体のこうげきを下げる", battle: { mpCost: 10, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "純白の守り", requiredStars: 5, description: "味方1人の守りを、とても大きく上げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 2.5, turns: 3 } },
      { name: "純白の裁き", requiredStars: 6, description: "白い光で敵全体を裁く", battle: { mpCost: 11, powerMultiplier: 1.8, effect: "damageAll" } },
      { name: "聖騎士の号令", requiredStars: 7, description: "号令で、味方全体のこうげきを上げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "純白の連撃", requiredStars: 7, description: "白い剣で、敵1体を3回斬る", battle: { mpCost: 12, powerMultiplier: 1.3, effect: "multi", hits: 3 } },
      { name: "聖域", requiredStars: 8, description: "聖域を張り、味方全体の守りを大きく上げる", battle: { mpCost: 15, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 1.7, turns: 3 } },
      { name: "純神の剣", requiredStars: 9, description: "純神の剣で、敵1体を斬る", battle: { mpCost: 15, powerMultiplier: 3.6 } },
      { name: "純白の息吹", requiredStars: 9, description: "白い息吹で、味方全体のHPを回復する", battle: { mpCost: 16, powerMultiplier: 0, effect: "healAll", healRatio: 2.0 } },
      { name: "聖騎士奥義・白き城壁", requiredStars: 10, description: "白き城壁で、味方全体の守りを、とても大きく上げる", battle: { mpCost: 24, powerMultiplier: 0, effect: "buffAll", stat: "defense", mult: 2.2, turns: 3 } },
    ],
  },
  {
    id: "demon-breaker", unlockFlag: "god3_defeated", maxStars: DIVINE_MAX_STARS, name: "鬼神の破戒者", reading: "きしんのはかいしゃ", role: "最高クラスの攻撃力。ただし、使うたびに自分のHPを支払う",
    statBonus: { attack: 14, defense: -3 }, bonusPerStar: { attack: 3 },
    skills: [
      { name: "破戒の拳", requiredStars: 1, description: "HPを少し支払い、敵1体を強く打つ", battle: { mpCost: 2, powerMultiplier: 2.2, hpCost: 0.05 } },
      { name: "破戒の一撃", requiredStars: 1, description: "HPを支払って、敵1体に強烈な一撃", battle: { mpCost: 3, powerMultiplier: 2.8, hpCost: 0.1 } },
      { name: "鬼の形相", requiredStars: 2, description: "おそろしい形相で、敵全体のこうげきを下げる", battle: { mpCost: 5, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.8, turns: 3, chance: 0.85 } },
      { name: "狂い打ち", requiredStars: 3, description: "HPを支払い、敵1体を3回打つ", battle: { mpCost: 4, powerMultiplier: 1.2, effect: "multi", hits: 3, hpCost: 0.08 } },
      { name: "鬼哭", requiredStars: 3, description: "HPを支払って、敵全体に叫びをぶつける", battle: { mpCost: 6, powerMultiplier: 2.0, effect: "damageAll", hpCost: 0.12 } },
      { name: "鬼神の血潮", requiredStars: 4, description: "HPを支払い、味方1人のこうげきを、とても大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "attack", mult: 1.8, turns: 3, hpCost: 0.1 } },
      { name: "破戒の連撃", requiredStars: 5, description: "HPを支払い、敵1体を4回打つ", battle: { mpCost: 7, powerMultiplier: 1.3, effect: "multi", hits: 4, hpCost: 0.1 } },
      { name: "骨砕き", requiredStars: 5, description: "敵1体の守りを、とても大きく下げる", battle: { mpCost: 6, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.55, turns: 3, chance: 0.85 } },
      { name: "修羅の滅", requiredStars: 6, description: "大きくHPを支払って、敵1体を打ち砕く", battle: { mpCost: 8, powerMultiplier: 4.5, hpCost: 0.2 } },
      { name: "鬼神の咆哮", requiredStars: 7, description: "HPを支払い、敵全体を打ちすえる", battle: { mpCost: 9, powerMultiplier: 2.6, effect: "damageAll", hpCost: 0.15 } },
      { name: "血の渇き", requiredStars: 7, description: "自分の減ったHPの半分を回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "restoreHalf" } },
      { name: "破戒の大斧", requiredStars: 8, description: "大きくHPを支払い、敵1体を断ち割る", battle: { mpCost: 9, powerMultiplier: 5.0, hpCost: 0.22 } },
      { name: "鬼の乱舞", requiredStars: 9, description: "HPを支払い、敵1体を6回打つ", battle: { mpCost: 11, powerMultiplier: 1.2, effect: "multi", hits: 6, hpCost: 0.18 } },
      { name: "修羅の嵐", requiredStars: 9, description: "大きくHPを支払い、敵全体を打ちくだく", battle: { mpCost: 13, powerMultiplier: 3.2, effect: "damageAll", hpCost: 0.2 } },
      { name: "鬼神奥義・天裂き", requiredStars: 10, description: "とても大きくHPを支払い、守りを無視して敵全体を裂く", battle: { mpCost: 18, powerMultiplier: 2.4, effect: "pierceAll", hpCost: 0.3 } },
    ],
  },
  {
    id: "bug-curser", unlockFlag: "god2_defeated", maxStars: DIVINE_MAX_STARS, name: "蟲神の呪術師", reading: "ちゅうしんのじゅじゅつし", role: "一撃で倒すチャンスを持つ。ただし強敵には効かず、確実ではない",
    statBonus: { maxMp: 14, speed: 6, defense: -2 }, bonusPerStar: { maxMp: 3, speed: 1 },
    skills: [
      { name: "蟲の噛みつき", requiredStars: 1, description: "小さな蟲が、敵1体に噛みつく", battle: { mpCost: 2, powerMultiplier: 1.4 } },
      { name: "蟲の囁き", requiredStars: 1, description: "小さな蟲の毒で、敵1体を弱らせる", battle: { mpCost: 3, powerMultiplier: 1.6 } },
      { name: "毒蟲", requiredStars: 2, description: "毒の蟲で、敵1体を毒にすることがある", battle: { mpCost: 4, powerMultiplier: 0, effect: "poison", chance: 0.85, turns: 4 } },
      { name: "惑い蟲", requiredStars: 3, description: "惑わす蟲で、敵1体を混乱させることがある", battle: { mpCost: 5, powerMultiplier: 0, effect: "confuse", chance: 0.65, turns: 2 } },
      { name: "理不尽の羽音", requiredStars: 3, description: "理由もなく命を刈る羽音。敵1体を、ときどき一撃で倒す（強敵には効かない）", battle: { mpCost: 8, powerMultiplier: 1.0, koChance: 0.18 } },
      { name: "眠り蟲", requiredStars: 4, description: "眠りの蟲で、敵1体を眠らせることがある", battle: { mpCost: 6, powerMultiplier: 0, effect: "sleep", chance: 0.75, turns: 2 } },
      { name: "蟲の群れ噛み", requiredStars: 5, description: "蟲の群れが、敵1体に4回噛みつく", battle: { mpCost: 8, powerMultiplier: 0.9, effect: "multi", hits: 4 } },
      { name: "腐らせの呪い", requiredStars: 5, description: "呪いで、敵1体の守りを、とても大きく下げる", battle: { mpCost: 7, powerMultiplier: 0, effect: "debuff", stat: "defense", mult: 0.55, turns: 3, chance: 0.85 } },
      { name: "蟲の大群", requiredStars: 6, description: "蟲の群れで敵全体を襲う", battle: { mpCost: 12, powerMultiplier: 2.0, effect: "damageAll" } },
      { name: "弱らせの呪い", requiredStars: 7, description: "呪いで、敵全体のこうげきを下げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "死の羽音", requiredStars: 7, description: "死を呼ぶ羽音。敵1体を、ときどき一撃で倒す（強敵には効かない）", battle: { mpCost: 12, powerMultiplier: 1.2, koChance: 0.3 } },
      { name: "蟲毒の霧", requiredStars: 8, description: "毒の霧で、敵全体の守りを下げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "debuffAll", stat: "defense", mult: 0.7, turns: 3, chance: 0.85 } },
      { name: "蟲神の呪い", requiredStars: 9, description: "蟲神の呪いで、敵全体のすばやさを大きく下げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "debuffAll", stat: "speed", mult: 0.6, turns: 3, chance: 0.85 } },
      { name: "蟲の津波", requiredStars: 9, description: "蟲の津波で、敵全体を飲みこむ", battle: { mpCost: 16, powerMultiplier: 2.6, effect: "damageAll" } },
      { name: "呪術奥義・虚ろの羽音", requiredStars: 10, description: "虚ろな羽音。敵1体を、ときどき一撃で倒す（強敵には効かない）", battle: { mpCost: 20, powerMultiplier: 2.0, koChance: 0.45 } },
    ],
  },
];

/**
 * レジェンドジョブ「灯心継承者」（主人公専用、`docs/design/jobs.md` 4章）。5系統すべてを、やや高いMPで扱える「何でも屋」。
 * 1点特化の強さは無く、上級ジョブを陳腐化させない。
 * 解放条件: 本編クリア後、仲間4人（レト・ミナ・コハク・オルカ）との絆（それぞれの寄り道サブストーリー）がそろい、カセンの手紙（S-025）を読んでいる。
 * （信頼度の数値は作らず、サブストーリーの完了で数える。`docs/decisions.md`）
 */
export const LEGEND_UNLOCK_FLAGS: string[] = [
  "chapter9_cleared",
  "side_s002_done", // レト
  "side_s004_done", "side_s010_done", // ミナ（幼なじみ前編・後編）
  "side_s006_done", "side_s007_done", // コハク
  "side_s009_done", "side_s011_done", // オルカ
  "side_s025_done", // カセンの手紙
];

export const LEGEND_JOBS: JobData[] = [
  {
    id: "torch-heir", unlockFlags: LEGEND_UNLOCK_FLAGS, heroOnly: true, name: "灯心継承者", reading: "とうしんけいしょうしゃ", role: "五系統の呪文をやや高いMPで扱う何でも屋",
    statBonus: { maxHp: 10, maxMp: 12, attack: 5, defense: 4, speed: 3 }, bonusPerStar: { maxHp: 2, maxMp: 3, attack: 1, defense: 1, speed: 1 },
    skills: [
      { name: "灯の火花", requiredStars: 1, description: "灯りの火花で、敵1体を打つ", battle: { mpCost: 2, powerMultiplier: 1.6 } },
      { name: "灯の一閃", requiredStars: 2, description: "灯りをまとった一撃で敵1体を斬る", battle: { mpCost: 5, powerMultiplier: 1.9 } },
      { name: "灯の守り", requiredStars: 3, description: "灯りの守りで、味方1人の守りを大きく上げる", battle: { mpCost: 4, powerMultiplier: 0, effect: "buff", stat: "defense", mult: 1.5, turns: 3 } },
      { name: "灯の癒し", requiredStars: 4, description: "灯りで味方1人のHPを回復する", battle: { mpCost: 8, powerMultiplier: 0, effect: "heal", healRatio: 2.0 } },
      { name: "灯の風", requiredStars: 5, description: "灯りの風で、味方全体のすばやさを上げる", battle: { mpCost: 9, powerMultiplier: 0, effect: "buffAll", stat: "speed", mult: 1.3, turns: 3 } },
      { name: "灯の波", requiredStars: 6, description: "灯りの波で敵全体を打つ", battle: { mpCost: 10, powerMultiplier: 1.3, effect: "damageAll" } },
      { name: "灯の眠り", requiredStars: 7, description: "やさしい灯りで、敵1体を眠らせることがある", battle: { mpCost: 7, powerMultiplier: 0, effect: "sleep", chance: 0.7, turns: 2 } },
      { name: "灯の慈雨", requiredStars: 8, description: "灯りの雨で味方全体を癒す", battle: { mpCost: 14, powerMultiplier: 0, effect: "healAll", healRatio: 1.3 } },
      { name: "灯の鎖", requiredStars: 9, description: "灯りの鎖で、敵全体のこうげきを下げる", battle: { mpCost: 11, powerMultiplier: 0, effect: "debuffAll", stat: "attack", mult: 0.75, turns: 3, chance: 0.85 } },
      { name: "灯心の共鳴", requiredStars: 10, description: "五つの系統を重ねて、敵1体に放つ", battle: { mpCost: 16, powerMultiplier: 3.2 } },
      { name: "灯の加護", requiredStars: 11, description: "灯りの加護で、味方全体のこうげきを上げる", battle: { mpCost: 12, powerMultiplier: 0, effect: "buffAll", stat: "attack", mult: 1.3, turns: 3 } },
      { name: "灯の大慈雨", requiredStars: 12, description: "大きな灯りの雨で、味方全体のHPを大きく回復する", battle: { mpCost: 18, powerMultiplier: 0, effect: "healAll", healRatio: 2.5 } },
      { name: "五灯連撃", requiredStars: 13, description: "五つの灯りで、敵1体を5回打つ", battle: { mpCost: 16, powerMultiplier: 1.3, effect: "multi", hits: 5 } },
      { name: "灯の大波", requiredStars: 14, description: "大きな灯りの波で、敵全体を打つ", battle: { mpCost: 18, powerMultiplier: 2.6, effect: "damageAll" } },
      { name: "灯心奥義・継ぎ火", requiredStars: 15, description: "受けついだ灯りのすべてが、守りを無視して敵全体を照らし打つ", battle: { mpCost: 26, powerMultiplier: 1.9, effect: "pierceAll" } },
    ],
  },
];

export const JOBS_BY_ID: Record<JobId, JobData> = Object.fromEntries(
  [...INITIAL_JOBS, ...ADVANCED_JOBS, ...DIVINE_JOBS, ...LEGEND_JOBS].map((job) => [job.id, job]),
) as Record<JobId, JobData>;

/**
 * そのキャラクターがいま装備できるジョブ（初期ジョブ8種と、初期ジョブを最大の☆まで育てて解放した上級ジョブ）。
 * 上級ジョブは初期ジョブの直後、天神・悪神ジョブ（8神を倒すと解放）、レジェンドジョブ（主人公だけ）はその後ろに並ぶ。
 */
export function availableJobs(
  masteryStars: (jobId: JobId) => number,
  flags: Record<string, boolean | undefined> = {},
  memberId?: string,
): JobData[] {
  return [
    ...INITIAL_JOBS,
    ...ADVANCED_JOBS.filter((job) => job.baseJob !== undefined && masteryStars(job.baseJob) >= MAX_STARS),
    ...DIVINE_JOBS.filter((job) => job.unlockFlag !== undefined && flags[job.unlockFlag] === true),
    ...LEGEND_JOBS.filter((job) => (!job.heroOnly || memberId === "hero") && (job.unlockFlags ?? []).every((f) => flags[f] === true)),
  ];
}

