"""4体の新しい頭（髪型）。仲間の髪型に似ないよう、髪は1から描いた（2026-10-07、人間の指示「髪の毛の感じが既存のドット絵に近いから気をつけて」）。
記号: A 縁取り / h 髪 / H 髪の明るい所 / d 髪の暗い所 / それ以外は各キャラの色（下のスクリプトで決める）。
'left' の向きを左右反転したものを 'right' に使う。行番号 → 16文字。"""

# エルフの弓使い（女性）: まっすぐな長い髪・まん中分け・葉の髪輪・とがった耳（体はアヤメの型）
ELF = {
 "down": {
  3: "......AAAA......",
  4: "....AAHHhdAA....",
  5: "...AHHHhhdddA...",
  6: "..AHHhhhhhddddA.",
  7: ".AHhhhhddhhhhdA.",
  8: ".AhhhhhddhhhhdA.",
  9: ".AhhhhdAAdhhhdA.",
  10: ".AccccgggcccccA.",
  11: ".AhhhdIIIIdhhdA.",
  12: ".AhhdIIIIIIdhdA.",
  13: "IAhIIIIIIIIIIhAI",
  14: "AAhIIKIIIIKIIhAA",
  15: ".AhIIKIIIIKIIhA.",
  16: ".AhMIIIIIIIIMhA.",
  17: ".AhANIIOOIINAhA.",
  18: ".AhAAAANNAAAAhA.",
 },
 "left": {
  3: "......AAAA......",
  4: ".....AHHhdAA....",
  5: "....AHHhhhddA...",
  6: "...AHhhhhhhddA..",
  7: "...AhhhhhhhhdA..",
  8: "..AhhhhhhhhhhdA.",
  9: "..AccggcccccccA.",
  10: "..AhhhhhhhhhhdA.",
  11: "..AhIIhhhhIhhdA.",
  12: "...AIIIhhhIIhdA.",
  13: "...AIIIIhhhhhdA.",
  14: "...AIKIIIhhhhdA.",
  15: "...AIKIIIAhhhdA.",
  16: "...AOIMIIAhhhdA.",
  17: "...AAIIIINAhhdA.",
  18: "....AANNAAAhhdA.",
 },
 "up": {
  3: "......AAAA......",
  4: "....AAHHhdAA....",
  5: "...AHHHhhdddA...",
  6: "..AHHhhhhhddddA.",
  7: ".AHhhhhhhhhhhdA.",
  8: ".AhhhhhhhhhhhdA.",
  9: ".AhhhhhhhhhhhdA.",
  10: ".AcccccgcccccA..",
  11: "AAhhhhhhhhhhhdAA",
  12: "IAhhhhhhhhhhhdAI",
  13: "AAhhhhhhhhhhhdAA",
  14: ".AhhhhhhhhhhhdA.",
  15: ".AhhhhhhhhhhhdA.",
  16: ".AhhhhhhhhhhhdA.",
  17: ".AhhhhhhhhhhhdA.",
  18: ".AddhhhhhhhhddA.",
 },
}

# 天使（男性）: 波打つ髪・横に流した前髪（体はレトの型。顔の行はレトのまま）
ANGEL = {
 "down": {
  3: "......AAAA......",
  4: "....AAHHHhAA....",
  5: "...AHHHHhhhdA...",
  6: "..AHHHhhdhhhdA..",
  7: ".AHHhhhhhhdhhdA.",
  8: ".AHhhdhhhhhhhdA.",
  9: ".AhhhhhhdhhhhdA.",
  10: "AhhhhhhhhhhhhdA.",
  11: ".AhhhhhhhhdEEdA.",
  12: ".AhhhhhdEEEEEdA.",
  13: ".AdhhdEEEEEEEdA.",
 },
 "left": {
  4: "......AAAA......",
  5: ".....AHHhhAA....",
  6: "....AHHhhdhhA...",
  7: "...AHhhhhhhdhA..",
  8: "..AHhhdhhhhhhdA.",
  9: "..AhhhhhhhdhhhA.",
  10: ".AhhhhhhhhhhhdA.",
  11: "..AhhhhhhhhhhdA.",
  12: "...AEEhhhhhhhdA.",
  13: "...AEEEEhhhhddA.",
 },
 "up": {
  3: "......AAAA......",
  4: "....AAHHHhAA....",
  5: "...AHHHHhhhdA...",
  6: "..AHHHhhdhhhdA..",
  7: ".AHHhhhhhhdhhdA.",
  8: ".AHhhdhhhhhhhdA.",
  9: ".AhhhhhhdhhhhdA.",
  10: ".AhhdhhhhhhdhdA.",
  11: ".AhhhhhhhhhhhdA.",
  12: ".AhhhhdhhhhhhdA.",
  13: ".AdhhhhhhhhhhdA.",
  14: ".AddhhhhhhhhddA.",
  15: "..AddhhhhhhddA..",
  16: "..AAddddddddAA..",
 },
}

# 悪魔（女性）: 高い位置の片側のポニーテール・ぱっつんの前髪（体はアヤメの型）
DEMON = {
 "down": {
  3: "......AAAA......",
  4: "....AAHhhdAA....",
  5: "...AHHhhhhddAAA.",
  6: "..AHHhhhhhhdAhdA",
  7: ".AHhhhhhhhhhdAhA",
  8: ".AhhhhhhhhhhdAhA",
  9: ".AhhhhhhhhhhhdhA",
  10: ".AhhhhhhhhhhhdA.",
  11: ".AdddddddddddAhA",
  12: ".AhIIIIIIIIIIhAh",
  13: ".AhIIIIIIIIIIhAh",
  14: ".AAIIKIIIIKIIAAh",
  15: "..AIIKIIIIKIIAdA",
  16: "..AMIIIIIIIIMAdA",
  17: "..AANIIOOIINAA.A",
  18: "...AAAANNAAAA...",
 },
 "left": {
  3: "......AAAA......",
  4: ".....AHhhdAA....",
  5: "....AHhhhhhdAAA.",
  6: "...AHhhhhhhhdhdA",
  7: "...AhhhhhhhhhdhA",
  8: "..AhhhhhhhhhhhdA",
  9: "..AhhhhhhhhhhdhA",
  10: "..AdddddhhhhhdA.",
  11: "...AIIIdhhhhdAhA",
  12: "...AIIIIdhhhdAhA",
  13: "...AIIIIIhhhdAdA",
  14: "...AIKIIIAhhdA..",
  15: "...AIKIIIAhdA...",
  16: "...AOIMIIAAA....",
  17: "...AAIIIINA.....",
  18: "....AANNAA......",
 },
 "up": {
  3: "......AAAA......",
  4: "....AAHhhdAA....",
  5: "...AHHhhhhddAAA.",
  6: "..AHHhhhhhhdAhdA",
  7: ".AHhhhhhhhhhdAhA",
  8: ".AhhhhhhhhhhdAhA",
  9: ".AhhhhhhhhhhhdhA",
  10: ".AhhhhhhhhhhhdA.",
  11: ".AhhhhhhhhhhhdAh",
  12: ".AhhhhhhhhhhhdAh",
  13: ".AdhhhhhhhhhddAh",
  14: ".AAddhhhhhhddAAh",
  15: "..AAddddddddAAdA",
  16: "...AAAAAAAAAA.dA",
  17: "..............A.",
  18: "................",
 },
}

# 魔王（男性）: 後ろへなでつけた長いたてがみ・広いおでこ（体はレトの型。顔の行はレトのまま）
LORD = {
 "down": {
  3: "......AAAA......",
  4: "....AAdhhdAA....",
  5: "...AdhHHhhhdA...",
  6: "..AdhHHHhhhhdA..",
  7: ".AdhhHhhhhhhhdA.",
  8: ".AdhhhhhhhhhhdA.",
  9: "AdhhhhhhhhhhhhdA",
  10: "AdhhhhhhhhhhhhdA",
  11: "AdhAAEEEEEEAAhdA",
  12: "AdhEEEEEEEEEEhdA",
  13: "AdhEEEEEEEEEEhdA",
 },
 "left": {
  4: "......AAAA......",
  5: ".....AdhhhAA....",
  6: "....AdhHHhhhA...",
  7: "...AdhHHhhhhhA..",
  8: "..AdhhhhhhhhhhA.",
  9: "..AhhhhhhhhhhhdA",
  10: "..AAAhhhhhhhhhdA",
  11: "..AEEAhhhhhhhhdA",
  12: "...AEEEdhhhhhhdA",
  13: "...AEEEEdhhhhhdA",
 },
 "up": {
  3: "......AAAA......",
  4: "....AAdhhdAA....",
  5: "...AdhHHhhhdA...",
  6: "..AdhHHHhhhhdA..",
  7: ".AdhhHhhhhhhhdA.",
  8: ".AdhhhhhhhhhhdA.",
  9: "AdhhhhhhhhhhhhdA",
  10: "AdhhhhdhhhhhhhdA",
  11: "AdhhhhhdhhhhhhdA",
  12: "AdhhhhhhdhhhhhdA",
  13: "AdhhhhhhhhhhhhdA",
  14: "AddhhhhhhhhhhddA",
  15: ".AddhhhhhhhhddA.",
  16: ".AAdddhhhhdddAA.",
  17: "..AAAddddddAAA..",
 },
}
for nm, H in (("ELF", ELF), ("ANGEL", ANGEL), ("DEMON", DEMON), ("LORD", LORD)):
    for d, rows in H.items():
        for y, r in rows.items():
            assert len(r) == 16, (nm, d, y, len(r), r)


# 魔王（2026-10-07、人間の指示「魔王の顔はおおもとの画像を忠実に再現してほしい」）:
# イメージ画像どおり、顔は見せず、黒いかぶとで全部おおう。まん中に赤く光る目が1つ、そこから赤い光が胸へ流れる。
# 頭の上にとがった前立て、左右から太い角が外へ張り出して上へ反る。
# 記号: h/H/d かぶと（地・明・暗）、k/l 角（地・明）、e 光の芯、r 赤い光、R 暗い赤い光
def _mirror(rows, keep_h_left=True):
    out = {}
    for y, half in rows.items():
        full = half + half[::-1]
        out[y] = "".join(("h" if (c == "H" and x >= 8) else c) for x, c in enumerate(full))
    return out


LORD_HELM = {
 "down": _mirror({
  0: ".AlA....",
  1: "AlkA....",
  2: "AlkA....",
  3: "AkkA...A",
  4: "AkkA..Ah",
  5: ".AkkAAdH",
  6: "..AkkdhH",
  7: "..AdkhHH",
  8: ".AdhhHHh",
  9: "AdhhhHhh",
  10: "Adhhhhhd",
  11: "AdhhhAdd",
  12: "AdhhAddr",
  13: "AdhhAdre",
  14: ".AdhAdrr",
  15: ".AdhhAdR",
  16: "..AdhhAR",
  17: ".AAAdhAR",
 }),
 "left": {
  0: "...AlA...AlA....",
  1: "...AlkA..AlkA...",
  2: "...AlkA..AlkA...",
  3: "....AkAAAAkA....",
  4: "....AkdhhhkAA...",
  5: "...AkdhHHhhkdA..",
  6: "...AdhHHhhhhhdA.",
  7: "..AdhHHhhhhhhdA.",
  8: "..AdhhhhhhhhhdA.",
  9: "..AdhhhhhhhhhhdA",
  10: "..AAddhhhhhhhhdA",
  11: ".AddrAhhhhhhhhdA",
  12: ".AdreAhhhhhhhhdA",
  13: "..AdrdAhhhhhhdA.",
  14: "..AddRdAhhhhddA.",
  15: "..AdddRAhhhddA..",
  16: "...AddRAAhddA...",
  17: "....AdRddAAA....",
 },
 "up": _mirror({
  0: ".AlA....",
  1: "AlkA....",
  2: "AlkA....",
  3: "AkkA...A",
  4: "AkkA..Ah",
  5: ".AkkAAdH",
  6: "..AkkdhH",
  7: "..AdkhHH",
  8: ".AdhhHHh",
  9: "AdhhhHhh",
  10: "Adhhhhhd",
  11: "Adhhhhhd",
  12: "Adhhhhhd",
  13: "Adhhhhhd",
  14: "AddhhhhD",
  15: ".AddhhhD",
  16: ".AAdddhD",
 }),
}
for d, rows in LORD_HELM.items():
    for y, r in rows.items():
        assert len(r) == 16, ("LORD_HELM", d, y, len(r), r)
